// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzNt_DbW5srgFmGEe2cFeyO2U9lLQ7cSI',
    appId: '1:4522788128:web:d7f41c317fd9c8c35e8345',
    messagingSenderId: '4522788128',
    projectId: 'socialmedia-88a17',
    authDomain: 'socialmedia-88a17.firebaseapp.com',
    storageBucket: 'socialmedia-88a17.firebasestorage.app',
    measurementId: 'G-B10P0YN1ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVcy0IE7EQaXyr6y92TLJVdYQTllWqaHo',
    appId: '1:4522788128:android:9c797b9e265c9ed85e8345',
    messagingSenderId: '4522788128',
    projectId: 'socialmedia-88a17',
    storageBucket: 'socialmedia-88a17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARhtfoTCs3DYlzGStpoSrrIaPJCE3bosk',
    appId: '1:4522788128:ios:89f07172683c7ceb5e8345',
    messagingSenderId: '4522788128',
    projectId: 'socialmedia-88a17',
    storageBucket: 'socialmedia-88a17.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARhtfoTCs3DYlzGStpoSrrIaPJCE3bosk',
    appId: '1:4522788128:ios:89f07172683c7ceb5e8345',
    messagingSenderId: '4522788128',
    projectId: 'socialmedia-88a17',
    storageBucket: 'socialmedia-88a17.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzNt_DbW5srgFmGEe2cFeyO2U9lLQ7cSI',
    appId: '1:4522788128:web:5aa16306db3378435e8345',
    messagingSenderId: '4522788128',
    projectId: 'socialmedia-88a17',
    authDomain: 'socialmedia-88a17.firebaseapp.com',
    storageBucket: 'socialmedia-88a17.firebasestorage.app',
    measurementId: 'G-181F6630KJ',
  );
}
